# --------------------------------------- Training -------------------------------------

NOTE: This section is for practising. Questions specified by Q are not a part of your coursework. You can check the comments to see what each cell does.

## Importing necessary Libraries

In [1]:
import pandas as pd 
import numpy as np

## Python Warmup exercises

* Q1: Write a code that receives an optional text, print all letters in the text and store them in a list

In [2]:
output=[]
text1='''welcome to workshop 1'''
for i in text1:
    print(i)
    output.append(i)
print(output)

w
e
l
c
o
m
e

t
o

w
o
r
k
s
h
o
p

1
['w', 'e', 'l', 'c', 'o', 'm', 'e', ' ', 't', 'o', ' ', 'w', 'o', 'r', 'k', 's', 'h', 'o', 'p', ' ', '1']

* Q2: Write a code that receives an optional text, prints all words in the text and store them in a list

In [3]:
output=[]
text1='''welcome to workshop 1'''
for word in text1.split():
    print(word)
    output.append(word)
print(output)

welcome
to
workshop
1
['welcome', 'to', 'workshop', '1']

* Q3: Write Q2 answer as a function

In [4]:
text1='''welcome to workshop 1'''
def print_word(text):
    for word in text.split():
        print(word)
print_word(text1)

welcome
to
workshop
1

* Q4: Write a program to find out the average of a set of integers. The program prompts the user to enter the count of numbers

In [ ]:
count = int(input("Enter the count of numbers: ")) # This gets the count of numbers from the user and 
# puts it in an integer variable
i = 0
sum = 0
for i in range(count):
    x = int(input("Enter an integer: "))
    sum = sum + x
avg = sum/count
print("The average is: ", avg)

* Q5: Write a program to check whether the given number is even or not.

In [ ]:
# If we divide an even number by 2, the remainder will be zero
number = input("Enter a number: ")
x = int(number)%2
if x == 0:
    print("The number is Even.")
else:
    print("The number is Odd.")

* Q6: Write a program to find the average of 4 numbers using while loop. The program prompts the user to enter the numbers

In [ ]:
count = 0
sum = 0.0
while(count<4):
    number = float(input("Enter a real number: "))
    count=count+1
    sum = sum+number
avg = sum/10
print("Average is :",avg)

* Q7: Write a function to find the average of a list of integers

In [8]:
def give_me_average(in_list):
    count=len(in_list)
    sum=0
    for i in in_list:
        sum=sum+i
    avg = sum/count
    return avg
a=[1,2,3,4]
print("Average is :",give_me_average(a))

Average is : 2.5

* Q8: Write a program to display all integers within the range 100-120 whose sum of digits is an even number and store them in a list

In [9]:
output=[]
for i in range(100,120):
    num = i
    sum = 0
    while(num!=0):
        digit = num%10
        sum = sum + digit
        num = num//10
    if(sum%2==0):
        output.append(i)
        print(i)
print(output)

101
103
105
107
109
110
112
114
116
118
[101, 103, 105, 107, 109, 110, 112, 114, 116, 118]

* Q9: Write a program to check whether the given integer is a multiple of both 5 and 7

In [10]:
number = int(input("Enter an integer: "))
if((number%5==0)and(number%7==0)):
    print(number, "is a multiple of both 5 and 7")
else:
    print(number, "is not a multiple of both 5 and 7")

Enter an integer:  1

1 is not a multiple of both 5 and 7

## Pandas warmup exercises

In [11]:
pip install pandas

Requirement already satisfied: pandas in ./anaconda3/lib/python3.11/site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in ./anaconda3/lib/python3.11/site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in ./anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

• You can install Pandas on your system by using pip as follows:
pip install pandas

• You can import Pandas as follows:
import pandas

• Pandas is usually imported under the pd alias.
import pandas as pd

• You can check Pandas version as follows:
import pandas as pd
print(pd.__version__)

In [8]:
import pandas

In [9]:
import pandas as pd

In [10]:
import pandas as pd
print(pd.__version__)

2.1.4

In [15]:
# You can use the DataFrame() method to create a Pandas DataFrame from a dictionary, numpy array, or a list.
data = {"calories": [420, 380, 390], "duration": [50, 40, 45]}
#load data into a DataFrame object:
df = pd.DataFrame(data)
print(df)
print('\n') # Addine an empty line to the end of the data frame
# ---
data = [[420, 380, 390],[50, 40, 45]]
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


     0    1    2
0  420  380  390
1   50   40   45

In [16]:
# You can use loc() or iloc() to return values, rows, or columns inside a data frame. Using loc() you need to specify the
# column name, but using iloc() you only need to specify the column index. 
data = {"calories": [420, 380, 390], "duration": [50, 40, 45]}
#load data into a DataFrame object:
df = pd.DataFrame(data)
print(df)
print("\n")
print(df.loc[0,'calories'])
print("\n")
print(df.loc[0,:])
print("\n")
print(df.iloc[:,0])

   calories  duration
0       420        50
1       380        40
2       390        45


420


calories    420
duration     50
Name: 0, dtype: int64


0    420
1    380
2    390
Name: calories, dtype: int64

In [17]:
# You can get the indices and columns names using index and column attributes as follows

data = {"calories": [420, 380, 390], "duration": [50, 40, 45]}
#load data into a DataFrame object:
df = pd.DataFrame(data)
index_names=list(df.index)
column_names=list(df.columns)
print(index_names,end='\n\n')
print(column_names)

[0, 1, 2]

['calories', 'duration']

In [18]:
# With the index and columns argument, you can name your own indexes and columns.
data = {
 "calories": [420, 380, 390],
 "duration": [50, 40, 45]
}
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [19]:
# With the index argument, you can name your own indexes and columns
data =[[420, 380, 390],[50, 40, 45]]
df = pd.DataFrame(data, columns = ["c1", "c2", "c3"])
print(df)

    c1   c2   c3
0  420  380  390
1   50   40   45

## Importing a dataset for this workshop

## Importing the dataset directly from the source

In [20]:
# Installing a package which is needed to download the dataset from its online source. This package is recommended by the online source at the following
# URL : https://archive.ics.uci.edu/dataset/2/adult
!pip3 install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
Downloading ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.3

In [ ]:
# Downloading the dataset from the online source. The first two lines are given by the online source mentioned above
from ucimlrepo import fetch_ucirepo 
# fetch dataset 
adult = fetch_ucirepo(id=2) 

# Putting data in a pandas dataframe
X = adult.data.features 
y = adult.data.targets 
data=pd.concat([X,y],axis=1)

In [ ]:
#printing data
data

## Importing the dataset from a folder on your local disk

In [4]:
import pandas as pd

# URL of the raw CSV file on GitHub
url = 'https://raw.githubusercontent.com/maz786/WlvMScAI/main/7CS033DataMining/Week1/adult.csv'

# Reading the dataset into a Pandas DataFrame
data = pd.read_csv(url)

# Display the first few rows of the DataFrame
print(data.head())

   age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13
1   50  Self-emp-not-inc   83311  Bachelors             13
2   38           Private  215646    HS-grad              9
3   53           Private  234721       11th              7
4   28           Private  338409  Bachelors             13

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male
1  Married-civ-spouse    Exec-managerial        Husband  White    Male
2            Divorced  Handlers-cleaners  Not-in-family  White    Male
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female

   capital-gain  capital-loss  hours-per-week native-country income
0          2174             0              40  United-States  <=50K
1             0             0              13  United-States  <=50K
2             0             0              40  United-States  <=50K
3             0             0              40  United-States  <=50K
4             0             0              40           Cuba  <=50K

## Exploring the dataset

In [5]:
# Showing the first 5 rows of the dataset
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
# Finding the shape of the data
print(data.shape)

(48842, 15)

In [7]:
# Generate a dataset by randomly extracting 30000 rows (samples) 
data_new = data.sample(n=30000, random_state = 48)

In [8]:
# Printing the new dataset
data_new

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
8029,29,Private,216481,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,>50K
45203,36,Private,280570,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,United-States,<=50K.
27498,25,?,100903,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,25,United-States,<=50K
48416,47,Private,145636,Assoc-voc,11,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,48,United-States,>50K.
43230,33,Private,119422,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37544,20,Private,166371,HS-grad,9,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,United-States,<=50K.
20482,80,Private,202483,HS-grad,9,Married-spouse-absent,Adm-clerical,Not-in-family,White,Female,0,0,16,United-States,<=50K
39667,20,Private,175808,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.
40001,25,State-gov,31350,Some-college,10,Never-married,Other-service,Not-in-family,White,Male,0,0,40,United-States,<=50K.
48523,19,Private,239057,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.

In [9]:
# The indices of different rows in the dataset are currently messy. This happens in many data science projects. Always reindex 
# the dataset if you are unsure the indices are correct.  
data_new.reset_index(drop=True, inplace=True)

In [10]:
# Checking if the indices are correct
data_new

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,29,Private,216481,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,>50K
1,36,Private,280570,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,United-States,<=50K.
2,25,?,100903,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,25,United-States,<=50K
3,47,Private,145636,Assoc-voc,11,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,48,United-States,>50K.
4,33,Private,119422,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,20,Private,166371,HS-grad,9,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,United-States,<=50K.
29996,80,Private,202483,HS-grad,9,Married-spouse-absent,Adm-clerical,Not-in-family,White,Female,0,0,16,United-States,<=50K
29997,20,Private,175808,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.
29998,25,State-gov,31350,Some-college,10,Never-married,Other-service,Not-in-family,White,Male,0,0,40,United-States,<=50K.
29999,19,Private,239057,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.

In [11]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [12]:
# Getting statistical information of the dataset for different columns (features) 
data.describe(include="all")

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
count,48842.000000,47879,4.884200e+04,48842,48842.000000,48842,47876,48842,48842,48842,48842.000000,48842.000000,48842.000000,48568,48842
unique,NaN,9,NaN,16,NaN,7,15,6,5,2,NaN,NaN,NaN,42,4
top,NaN,Private,NaN,HS-grad,NaN,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,NaN,NaN,United-States,<=50K
freq,NaN,33906,NaN,15784,NaN,22379,6172,19716,41762,32650,NaN,NaN,NaN,43832,24720
mean,38.643585,NaN,1.896641e+05,NaN,10.078089,NaN,NaN,NaN,NaN,NaN,1079.067626,87.502314,40.422382,NaN,NaN
std,13.710510,NaN,1.056040e+05,NaN,2.570973,NaN,NaN,NaN,NaN,NaN,7452.019058,403.004552,12.391444,NaN,NaN
min,17.000000,NaN,1.228500e+04,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,NaN,NaN
25%,28.000000,NaN,1.175505e+05,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
50%,37.000000,NaN,1.781445e+05,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
75%,48.000000,NaN,2.376420e+05,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,45.000000,NaN,NaN
max,90.000000,NaN,1.490400e+06,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,99999.000000,4356.000000,99.000000,NaN,NaN

In [13]:
# Droping row with Null values (This topic will be discussed in detail in the next lecture)
data.dropna(inplace=True)

In [14]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48836,33,Private,245211,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K.
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

NOTE: As you can see, because a few rows have been dropped, the index numbers don't correspond to the actual row number (the number of rows is 47623 but the last index is 48841). We need to reindex the data

In [15]:
# reindexing the original data
data.reset_index(drop=True, inplace=True)

In [16]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47616,33,Private,245211,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K.
47617,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
47618,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
47619,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
47620,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [17]:
# Getting the number of Null values for different columns
data.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [18]:
# Showing the dataset information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47621 entries, 0 to 47620
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             47621 non-null  int64
 1   workclass       47621 non-null  object
 2   fnlwgt          47621 non-null  int64
 3   education       47621 non-null  object
 4   education-num   47621 non-null  int64
 5   marital-status  47621 non-null  object
 6   occupation      47621 non-null  object
 7   relationship    47621 non-null  object
 8   race            47621 non-null  object
 9   sex             47621 non-null  object
 10  capital-gain    47621 non-null  int64
 11  capital-loss    47621 non-null  int64
 12  hours-per-week  47621 non-null  int64
 13  native-country  47621 non-null  object
 14  income          47621 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.4+ MB

In [19]:
data.shape

(47621, 15)

In [20]:
# Getting the count of different values in the column "education-num"
data['education-num'].value_counts()

education-num
9     15444
10    10512
13     7881
14     2610
11     2034
7      1746
12     1566
6      1336
4       912
15      819
5       735
8       633
16      582
3       494
2       239
1        78
Name: count, dtype: int64

In [21]:
# Getting the count of different values in the column "education"
data['education'].value_counts()

education
HS-grad         15444
Some-college    10512
Bachelors        7881
Masters          2610
Assoc-voc        2034
11th             1746
Assoc-acdm       1566
10th             1336
7th-8th           912
Prof-school       819
9th               735
12th              633
Doctorate         582
5th-6th           494
1st-4th           239
Preschool          78
Name: count, dtype: int64

In [22]:
# Dropping a column
data = data.drop(['fnlwgt'], axis=1)

In [23]:
data.shape

(47621, 14)

In [24]:
# Getting the number of unique values of a column
data['education'].nunique()

16

In [25]:
# Finding how many rows are related to either gender 
data['sex'].value_counts()

sex
Male      31937
Female    15684
Name: count, dtype: int64

In [26]:
# Calculating the average age of different genders in the dataset 
data['age'].groupby([data['sex']]).mean()

sex
Female    36.961043
Male      39.465542
Name: age, dtype: float64

In [27]:
# Getting the average age of different genders in the dataset broken down based on their education
data['age'].groupby([data['sex'],data['education']]).mean()

sex     education
Female  10th            36.520642
        11th            29.891410
        12th            29.716418
        1st-4th         46.508475
        5th-6th         45.346774
        7th-8th         51.088889
        9th             41.566038
        Assoc-acdm      36.402619
        Assoc-voc       38.000000
        Bachelors       35.747837
        Doctorate       45.557522
        HS-grad         38.862285
        Masters         42.520482
        Preschool       44.409091
        Prof-school     40.131783
        Some-college    33.778719
Male    10th            38.406667
        11th            33.479185
        12th            33.842593
        1st-4th         46.050000
        5th-6th         42.524324
        7th-8th         48.608443
        9th             40.556405
        Assoc-acdm      38.537173
        Assoc-voc       38.853881
        Bachelors       40.190319
        Doctorate       47.936034
        HS-grad         39.073626
        Masters         44.584270
        Preschool       41.160714
        Prof-school     46.017391
        Some-college    37.176643
Name: age, dtype: float64

In [28]:
# Getting the maximum age of different races in the dataset
data['age'].groupby([data['race']]).max()

race
Amer-Indian-Eskimo    82
Asian-Pac-Islander    90
Black                 90
Other                 77
White                 90
Name: age, dtype: int64

In [29]:
# Extracting the age and education columns and creating a new DataFrame using these columns
a=data['age']
b=data['education']
new_data=pd.concat([a,b],axis=1)

In [30]:
data

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47616,33,Private,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K.
47617,39,Private,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
47618,38,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
47619,44,Private,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
47620,35,Self-emp-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

* Q10: Write a function that receives the dataset and replace Famle with F and Male with M (please try to write it yourself before checking the answer in the next cell)

In [31]:
# Answer
def encode_sex(data):
    rows=data.shape[0]
    a=data.loc[:,'sex']
    for i in range(rows): 
        if a[i]=="Male":
            data.loc[i,"sex"]="M"
        elif a[i]=="Female":
            data.loc[i,"sex"]="F"
    return data

In [32]:
# Copying the data
data_copy=data.copy()

In [33]:
# Applying the encode_sex function to the copied data
data_encoded=encode_sex(data_copy)
data_encoded.head()

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,M,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,M,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,M,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,M,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,F,0,0,40,Cuba,<=50K

In [46]:
data

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47616,33,Private,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K.
47617,39,Private,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
47618,38,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
47619,44,Private,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
47620,35,Self-emp-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

# Tasks

## TASK 1.1: Import the dataset from the URL we used in this workshop. Then generate a new dataset by randomly extracting 10000 samples. Reindex the generated dataset and remove NULL values. Name the new dataset 'task_dataset'

In [11]:
import pandas as pd

url = 'https://raw.githubusercontent.com/maz786/WlvMScAI/main/7CS033DataMining/Week1/adult.csv'

data = pd.read_csv(url)

task_dataset = data.sample(n=10000, random_state=42)

task_dataset.reset_index(drop=True, inplace=True)

task_dataset.dropna(inplace=True)

print(task_dataset.head())

   age  workclass  fnlwgt     education  education-num marital-status  \
0   18    Private  423024       HS-grad              9  Never-married
1   17    Private  178953          12th              8  Never-married
2   25  Local-gov  348986       HS-grad              9  Never-married
3   20    Private  218215  Some-college             10  Never-married
4   47    Private  244025       HS-grad              9  Never-married

          occupation    relationship                race     sex  \
0      Other-service   Not-in-family               White    Male
1              Sales       Own-child               White  Female
2  Handlers-cleaners  Other-relative               Black    Male
3              Sales       Own-child               White  Female
4  Machine-op-inspct       Unmarried  Amer-Indian-Eskimo    Male

   capital-gain  capital-loss  hours-per-week native-country income
0             0             0              20  United-States  <=50K
1             0             0              20  United-States  <=50K
2             0             0              40  United-States  <=50K
3             0             0              30  United-States  <=50K
4             0             0              56    Puerto-Rico  <=50K

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

## TASK 1.2: Write a code to find how much contribution each sex and occupation category made to the capital-gain on average. Apply the code to the task_dataset and report the result (Hint: you need to use the groupby method)

In [12]:
average_capital_gain = task_dataset.groupby(['sex', 'occupation'])['capital-gain'].mean()

print(average_capital_gain)

sex     occupation
Female  ?                     657.111111
        Adm-clerical          584.281088
        Craft-repair          204.825397
        Exec-managerial      1130.724138
        Farming-fishing       958.260870
        Handlers-cleaners       0.000000
        Machine-op-inspct     125.893750
        Other-service         101.237410
        Priv-house-serv       114.722222
        Prof-specialty       1106.946988
        Protective-serv       626.760000
        Sales                 263.618582
        Tech-support          166.681416
        Transport-moving      312.419355
Male    ?                     838.892704
        Adm-clerical          472.453083
        Armed-Forces            0.000000
        Craft-repair          646.430868
        Exec-managerial      2355.091324
        Farming-fishing      1271.208054
        Handlers-cleaners     151.812139
        Machine-op-inspct     594.172867
        Other-service         131.432836
        Priv-house-serv         0.000000
        Prof-specialty       3240.946429
        Protective-serv       415.945652
        Sales                1884.821277
        Tech-support          704.227545
        Transport-moving      341.561404
Name: capital-gain, dtype: float64

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

## TASK 1.3: Write a code to find the country with the highest number of people with a Bachelors degree. Apply the code to the task_dataset and report the result (Hint: you need to use the groupby method)

In [13]:
bachelors_data = task_dataset[task_dataset['education'] == 'Bachelors']

country_counts = bachelors_data.groupby('native-country').size()

highest_bachelors = country_counts.idxmax()

print(f"The country with the highest number of people with a Bachelor's degree is: {highest_bachelors}")

The country with the highest number of people with a Bachelor's degree is: United-States

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

## TASK 1.4: Write a code to receive two lists including five names and their respective ages and print 'Hello Name Age' 
## For example, if it received a list of two names ['Amin', 'Michael'] and respective ages [27,38], it would print 'Hello Amin 27', 'Hello Michael 38'. Each hello statement should be printed in a new line

In [14]:
def print_greetings(names, ages):
    for name, age in zip(names, ages):
        print(f"Hello {name} {age}")

names = ['Amin', 'Michael']
ages = [27, 38]
print_greetings(names, ages)

Hello Amin 27
Hello Michael 38

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

## TASK 1.5: Write a code to receive an optional text, capitalise all words in the text and print them

In [15]:
def capitalize_text(text=""):
    capitalized_text = text.title()

    print(capitalized_text)

text = "this is an example text"
capitalize_text(text)

capitalize_text()

This Is An Example Text

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

## TASK 1.6: Write a function to split the task_dataset in half column-wise and swap the first half and the second half

In [16]:
def swap_dataset_columns(data):
    midpoint = data.shape[1] // 2

    first_half = data.iloc[:, :midpoint]
    second_half = data.iloc[:, midpoint:]

    swapped_data = pd.concat([second_half, first_half], axis=1)

    return swapped_data

swapped_task_dataset = swap_dataset_columns(task_dataset)

print(swapped_task_dataset.head())

     relationship                race     sex  capital-gain  capital-loss  \
0   Not-in-family               White    Male             0             0
1       Own-child               White  Female             0             0
2  Other-relative               Black    Male             0             0
3       Own-child               White  Female             0             0
4       Unmarried  Amer-Indian-Eskimo    Male             0             0

   hours-per-week native-country income  age  workclass  fnlwgt     education  \
0              20  United-States  <=50K   18    Private  423024       HS-grad
1              20  United-States  <=50K   17    Private  178953          12th
2              40  United-States  <=50K   25  Local-gov  348986       HS-grad
3              30  United-States  <=50K   20    Private  218215  Some-college
4              56    Puerto-Rico  <=50K   47    Private  244025       HS-grad

   education-num marital-status         occupation
0              9  Never-married      Other-service
1              8  Never-married              Sales
2              9  Never-married  Handlers-cleaners
3             10  Never-married              Sales
4              9  Never-married  Machine-op-inspct

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

## Task 1.7: Write a function that receives two numerical columns' names and compare their values for all rows. If the value of the first column is greater than the second column, the function should produce True, otherwise, it should produce False. The function should append an additional column to the dataset to store the results of the comparison for all rows. Apply the function to the "age" and "hours-per-week" columns in the task_dataset and print the result.

In [17]:
def compare_columns_and_append(data, col1, col2, new_col_name):
    comparison_result = data[col1] > data[col2]

    data[new_col_name] = comparison_result

compare_columns_and_append(task_dataset, 'age', 'hours-per-week', 'age_greater_than_hours_per_week')

print(task_dataset[['age', 'hours-per-week', 'age_greater_than_hours_per_week']].head())

   age  hours-per-week  age_greater_than_hours_per_week
0   18              20                            False
1   17              20                            False
2   25              40                            False
3   20              30                            False
4   47              56                            False

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

## Task 1.8: Write a function that returns the names of countries with maximum and minimum average ages in the task_dataset (Hint: you can use the numpy module)

In [18]:
import numpy as np

def find_countries_with_extreme_ages(data):
    average_ages = data.groupby('native-country')['age'].mean()

    max_age_country = average_ages.idxmax()
    max_age_value = np.max(average_ages)

    min_age_country = average_ages.idxmin()
    min_age_value = np.min(average_ages)

    return max_age_country, max_age_value, min_age_country, min_age_value

max_age_country, max_age_value, min_age_country, min_age_value = find_countries_with_extreme_ages(task_dataset)

print(f"Country with maximum average age: {max_age_country} (Average Age: {max_age_value})")
print(f"Country with minimum average age: {min_age_country} (Average Age: {min_age_value})")

Country with maximum average age: Yugoslavia (Average Age: 55.5)
Country with minimum average age: Ireland (Average Age: 31.333333333333332)

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############